---
name: cross-fire_nexxus
services:
  vscode:
    container_name: nexxus-vscode
    command: sleep infinity

    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    environment:
      TZ: ${TZ:-America/Chicago}

    volumes:
      - ..:/workspace:cached

    labels:
      - "traefik.enable=false"

    networks:
      - nexxus

  mysql:
    container_name: nexxus-mysql
    image: mysql:lts
    restart: unless-stopped

    cap_add:
      - SYS_NICE

    command: >
      --general-log=0
      --slow-query-log=1
      --log-queries-not-using-indexes=1
      --long-query-time=10
      --max_allowed_packet=256M
      --net_read_timeout=600
      --net_write_timeout=600
      --wait_timeout=28800
      --interactive_timeout=28800

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${TZ}
      MYSQL_INNODB_BUFFER_POOL_SIZE: 512M
      MYSQL_INNODB_LOG_FILE_SIZE: 128M

    volumes:
      - mysql_data:/var/lib/mysql
      - "./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro"
      - /dev/log:/dev/log

    ports:
      - "3306:3306"

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

    labels:
      - "traefik.enable=false"

    networks:
      - nexxus

networks:
  nexxus:
    name: nexxus
    driver: bridge
    external: true

volumes:
  mysql_data:
