---
http:
  middlewares:
    redirect-https:
      redirectScheme:
        scheme: https
        permanent: true

    security-headers:
      headers:
        stsSeconds: 63072000
        stsIncludeSubdomains: true
        frameDeny: true
        contentTypeNosniff: true
        referrerPolicy: "same-origin"

    compress-response:
      compress: {}

  routers:
    dokuwiki-block-badbots:
      priority: 1000
      rule: >
        Host(`wiki.cross-fire.org`)
        && HeadersRegexp(`User-Agent`, `(?i)(BLEXBot|ClaudeBot|meta-externalagent|CMS-Checker)`)
      entryPoints:
        - websecure
      service: noop@internal
      tls:
        certResolver: letsencrypt

    dokuwiki-http-redir:
      priority: 10
      rule: "Host(`wiki.cross-fire.org`)"
      entryPoints:
        - web
      middlewares:
        - redirect-https
      service: noop@internal
      tls: false

    dokuwiki-https:
      rule: "Host(`wiki.cross-fire.org`)"
      entryPoints:
        - websecure
      service: dokuwiki-service
      tls:
        certResolver: letsencrypt
      middlewares:
        - security-headers
        - compress-response

  services:
    dokuwiki-service:
      loadBalancer:
        passHostHeader: true
        serversTransport: dokuwiki-transport
        servers:
          - url: "http://dokuwiki:8080"

  serversTransports:
    dokuwiki-transport:
      forwardingTimeouts:
        dialTimeout: 10s
        responseHeaderTimeout: 300s
        idleConnTimeout: 300s
      maxIdleConnsPerHost: 200
