# Generated by Django 5.1.7 on 2025-03-09 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blacklist",
            fields=[
                ("entry", models.AutoField(primary_key=True, serialize=False)),
                ("hostname", models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                "db_table": "blacklist",
            },
        ),
        migrations.CreateModel(
            name="Server",
            fields=[
                ("entry", models.AutoField(primary_key=True, serialize=False)),
                ("hostname", models.CharField(blank=True, max_length=80, null=True)),
                ("port", models.IntegerField(blank=True, null=True)),
                ("html_comment", models.CharField(blank=True, max_length=1024, null=True)),
                ("text_comment", models.CharField(blank=True, max_length=256, null=True)),
                ("archbase", models.CharField(blank=True, max_length=64, null=True)),
                ("mapbase", models.CharField(blank=True, max_length=64, null=True)),
                ("codebase", models.CharField(blank=True, max_length=64, null=True)),
                ("flags", models.CharField(blank=True, max_length=20, null=True)),
                ("num_players", models.IntegerField(blank=True, null=True)),
                ("in_bytes", models.IntegerField(blank=True, null=True)),
                ("out_bytes", models.IntegerField(blank=True, null=True)),
                ("uptime", models.IntegerField(blank=True, null=True)),
                ("version", models.CharField(blank=True, max_length=64, null=True)),
                ("sc_version", models.CharField(blank=True, max_length=20, null=True)),
                ("cs_version", models.CharField(blank=True, max_length=20, null=True)),
                ("last_update", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "servers",
            },
        ),
    ]
