# Generated by Django 5.1.7 on 2025-03-11 17:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nexxus", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="server",
            name="last_update",
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
