# Generated by Django 5.2 on 2025-04-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nexxus", "0002_alter_server_last_update"),
    ]

    operations = [
        migrations.AddField(
            model_name="blacklist",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
