# Generated by Django 5.2 on 2025-04-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nexxus", "0003_blacklist_ip_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="server",
            name="port",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
